name: HypixelDragon
main: com.example.hypixeldragon.HypixelDragonPlugin
version: 1.0
api-version: 1.20
commands:
  spawnhdrag:
    description: Spawn a Hypixel-style Ender Dragon
    usage: /spawnhdrag
permissions:
  hypixeldragon.spawn:
    description: Allows spawning the custom dragon
    default: op