name: HypixelDragon
main: com.example.hypixeldragon.HypixelDragonPlugin
version: 1.0
api-version: 1.20
commands:
  spawnhdrag:
    description: Spawns a Hypixel-style Ender Dragon in The End.
    usage: /spawnhdrag
